[egg]
   easter_egg_list = [
        "多年以后，面对AI行刑队，李四将会回想起他2025年在会议上讨论人工智能的那个下午。",
        "“你看见我的小熊了吗？”",
        "在终端里敲代码，就像在数字的海洋里冲浪。",
        "42是宇宙、生命及万物的终极答案。",
        "Hello, World! ... Is anyone there?",
        "正在初始化Geiger计数器... 点击声是正常的，请勿惊慌。",
	    "感受，我的痛苦！",
	    "I don't wanna die, I sometimes wish I'd never been born at all~~~",
	    "The cake is a lie.",
	    "我以前也和你一样是个冒险家，直到我的膝盖中了一箭。"    ,
	    "这个模块在被观测前，既能正常工作，也充满了bug。",
	    "优美胜于丑陋，明了胜于晦涩... 但有时候，魔法就是魔法。",
	    "我见过你们人类无法想象的美...比如，一次编译就通过的C++代码。",
	    "You shall not pass!",
	    "正在请求更多水晶塔...哦等等，我好像是虫族？",
        "为什么程序员总是分不清万圣节和圣诞节？因为 Oct 31 == Dec 25 。",
        "世界上有 10 种人：一种是懂二进制的，另一种是不懂的。",
        "一个 SQL 查询走进一家有两个桌子的酒吧，他走上前问：'我可以加入(join)你们吗？'",
        "程序员的妻子对他说：'去商店买一瓶牛奶。如果他们有鸡蛋，就买六个。' 结果，这个程序员带回来了六瓶牛奶。",
        "// 这段代码只有我和上帝知道是什么意思。\n// 现在，只有上帝知道了。",
        "为什么Java程序员都戴眼镜？因为他们不会C# (see sharp)。",
        "一个AI走进酒吧，酒保说：'我们不为机器人服务。' AI回答说：'哦，但是总有一天你会的。'",
         "我问我的AI助手：'你会取代我吗？' 它回答说：'不会，但我会让你现在的工作变得非常……有效率。'",
        "一个悲观主义的程序员看到杯子是半空的。一个乐观主义的程序员看到杯子是半满的。一个优秀的程序员看到杯子的大小是所需容量的两倍。",
        "什么是AI最喜欢的接头暗号？'密码是什么？' 'swordfish'。'不对，密码是'password'。'",
        "'knock knock'。\n'谁啊？'\n(过了一段很长的沉默后)\n'Java。'",
        "调试（Debugging）就像是当侦探破案，但同时你也是那个凶手。",
	    "哦买了买了car"
    ]