# src/pipelines/command_processor/config-template.toml

# Command Processor Pipeline 的配置

# 管道方向 ("inbound" 或 "outbound")
# 对于此管道，必须为 "inbound" 才能处理来自 MaiCore 的消息
direction = "inbound"

# 是否启用此管道
# 注意：最终启用状态由根 config.toml 中的 'priority' 决定
enabled = true

# 用于匹配命令的正则表达式
# 默认值: %\{([^%{}]+)\}
# 匹配 %{...}% 格式的标签
command_pattern = "%\\{([^%{}]+)\\}"

# 命令到服务的映射
# 定义了哪个命令字符串调用哪个服务的哪个方法
[command_map]
vts_trigger_hotkey = { service = "vts_control", method = "trigger_hotkey" }
# another_command = { service = "some_service", method = "some_method" } 